tandeem:
    resource: "@TandeemBundle/Resources/config/routing.yml"
    prefix:   /

entity:
    resource: "@EntityBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
