tandeem_homepage:
    path:     /
    defaults: { _controller: TandeemBundle:Default:index }

Blog:
    path: /Blog
    defaults: { _controller: TandeemBundle:Blog:index }

Show_Posts:
    path: /Posts
    defaults: { _controller: TandeemBundle:Posts:show }

Create_Posts:
    path: /CreatePosts
    defaults: { _controller: TandeemBundle:Posts:index }

Upload_Posts:
    path: /createPosts/create
    defaults: { _controller: TandeemBundle:Posts:create }

Delete_Posts:
    path: /Post/delete
    defaults: { _controller: TandeemBundle:Posts:delete }

Post:
    path: /Post/{id}
    defaults: { _controller: TandeemBundle:Posts:showOne }

Create_Comments:
    path: /Comments/Create
    defaults: { _controller: TandeemBundle:Comments:createComments }

Delete_Comments:
    path: /Comments/Delete
    defaults: { _controller: TandeemBundle:Comments:delete }

Show_user_Admin:
    path: /Users
    defaults: { _controller: TandeemBundle:Blog:showUser }

Delete_User:
    path: /Users/delete
    defaults: { _controller: TandeemBundle:Blog:deleteUser }
